--- 
- hosts: loadbalancer
  # gather_facts: true
  become: yes
  name: Setup machine

  tasks: # list
    - name: Setup network configuration
      # when: false
      include_role:
        name: linux-system-roles.network
      vars:
        # network_provider: nm
        network_connections:
          - name: "{{item.name}}"
            # interface_name: same
            type: ethernet
            persistent_state: present
            autoconnect: yes
            state: up
            mac: "{{item.mac}}"
            ip:
              dhcp4: no
              address: "{{item.static_ip}}"
              gateway4: "{{item.gateway_ip}}" 
              dns:
                - "{{item.dns.dns1}}"
                - "{{item.dns.dns2}}"
          # - persistent_state: absent  # remove other existing configure profile
      loop: "{{net_config}}"

    - name: Install the latest version of DHCP server
      # when: false
      become: yes
      ansible.builtin.package:
        name:
          - dhcp-server
        state: present

    - name: Apply Page Template
      # when: false
      template:
        src: templates/dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
      vars: 
        args: "{{dhcpd_conf}}"
          
    - name: Start DHCP Server service
      # when: false
      service:
        name: dhcpd
        state: started # restarted
        enabled: yes
      become: yes