--- 
- hosts: loadbalancer
  # gather_facts: false
  name: Setting Static Ip
  become: yes
  vars:
    # network_provider: nm
    network_connections:
      - name: "{{prv_net.name}}"
        #persistent_state: present  # default
        type: ethernet
        autoconnect: yes
        state: up
        mac: "{{prv_net.mac}}"
        ip:
          dhcp4: no
          address: "{{prv_net.static_ip}}"
          gateway4: "{{prv_net.gateway_ip}}" 
          dns:
            - "{{prv_net.dns.dns1}}"
            - "{{prv_net.dns.dns2}}"
  roles:
    - linux-system-roles.network

      