--- 
- hosts: loadbalancer
  become: yes
  # gather_facts: false
  name: Setting Static IP

  tasks: # list
    - name: Install needed network manager libs
      ansible.builtin.package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - python3-libsemanage
          - python3-policycoreutils
        state: present

    - name: Try nmcli add Ethernet - conn_name only & ip4 gw4
      community.general.nmcli:
        state: present
        type: ethernet
        mac: e4:43:4b:12:e7:4a
        conn_name: eth2_internal_network
        # ifname: eth22
        ip4: 192.168.1.1/24
        gw4: 192.168.1.1
      # with_items: "{{prv_net}}"
      # register: echo