---
- name: Install docker with YUM
  # gather_facts: false
  hosts: worker1
  become: true
  vars:
    docker_version: "20.10.9"

  tasks:
    - name: Uninstall old versions
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: 
          # - "docker-ce{{ '-' + docker_version | default(omit)}}"
          # - "docker-ce-cli{{ '-' + docker_version | default(omit)}}"
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        # allowerasing: yes
      become: yes

    - name: Add ansible_user to docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
      become: yes

    - name: adding existing user '"{{ ansible_ssh_user }}"' to group sudo
      user:
        name: '{{ ansible_ssh_user }}'
        groups: docker
        append: yes
      become: yes
    
    - name: refresh existing user group
      shell: newgrp
      async: 2
      poll: 1

    - name: reset ssh connection allowing new group to present
      meta: reset_connection

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Start Containerd service
      service:
        name: containerd
        state: started
        enabled: yes
      become: yes

    - name: install python3 and pip
      package:
        name: 
          - python3
          - python3-pip
        state: present
      become: yes

    # - name: pip install docker sdk
    #   shell: pip3 install docker
      # pip:
      #   name: docker

    # - name: run hello-world
    #   community.docker.docker_container:
    #     name: hello-world
    #     image: hello-world
    #     state: started
    #   register: docker_output
    
    # - debug:
    #     var: docker_output.stdout_lines

    - name: Create a directory for Docker Cli Plugin if it does not exist
      file:
        path: "/home/{{ansible_user}}/.docker/cli-plugins/"
        state: directory
        mode: '0755'

    - name: Download Docker Compose V2
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        dest: "/home/{{ansible_user}}/.docker/cli-plugins/docker-compose"
        mode: '777'

    - name: Docker Compose V2 
      ansible.builtin.shell: docker compose version
      register: docker_compose
    
    - debug: 
        var: docker_compose.stdout_lines