--- 
- hosts: idrac
  connection: local
  gather_facts: false
  name: Booting to Network Operating System image

  collections:
    - dellemc.openmanage

  tasks: 
    - name: "Booting to Network Operating System image"
      idrac_os_deployment:
        idrac_ip: "192.168.11.76"
        idrac_user: "root"
        idrac_password:  "3333"
        validate_certs: False
        share_name: "192.168.11.222:/mnt/mydrive/shared"
        iso_image: "centos8-full.iso"        
        expose_duration: 180

      tags:
        - network_iso