--- 
- hosts: idrac
  connection: local
  gather_facts: false
  name: Booting to Network Operating System image

  collections:
    - dellemc.openmanage

  tasks: 
    - name: "Booting to Network Operating System image"
      idrac_os_deployment:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password:  "{{ idrac_password }}"
        validate_certs: False
        share_name: "{{ playbook_dir }}"
        iso_image: "centos8-full.iso"        
        expose_duration: 180

      tags:
        - network_iso