--- 
- hosts: idrac
  connection: local
  gather_facts: false
  name: Power Up Dell PowerEdge

  collections:
    # - dellemc.openmanage
    - dellemc.openmanage.redfish_powerstate

  tasks: # list
    - name: Manage power state of the first device
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ idrac_ip }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: "False"
        reset_type: "On" # On ForceOff/On/Restart GracefullRestart/Shutdown PushPowerButton PowerCycle Nmi
      tags:
        - idrac