--- 
- hosts: minio #:!poweredge83 #:!pfsense
  connection: local
  gather_facts: false
  name: Power Up Dell PowerEdge

  collections:
    # - dellemc.openmanage
    - dellemc.openmanage.redfish_powerstate
  tasks:
    - name: Manage power state of the first device
      # when: False
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ idrac_ip }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: "False"
        reset_type: "{{command}}" # ForceOff, ForceOn, ForceRestart, GracefulRestart, GracefulShutdown, Nmi, On, PowerCycle, PushPowerButton
      tags:
        - idrac