---
- name: Install docker with YUM
  # gather_facts: false
  hosts: poweredge83

  tasks:
    - name: Install the nginx rpm from a remote repo
      package:
        name: https://repo.roxy-wi.org/roxy-wi-release-7-2-3.noarch.rpm 
        state: present
      become: yes

    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/roxy-wi.repo
        line: baseurl=https://login:password@repo.roxy-wi.org/$ostype$releasever/
        create: yes
      become: yes